### ISSUE TITLE
Pattern- Leadspace:- Spacing issue between headline and copy text on entering more than two line of text

### ISSUE THREAD

**Issue by chetankan** [carbon-design-system/ibm-dotcom-library#1576]
Issue:- In leadspace pattern required spacing is not maintained on entering more than two line of text in headline and copy text . Happening on desktop and mobile
## Steps to reproduce the issue

1. Enter url in the browser.
2. Open 'Leadspace' pattern
3. Enter text in both headline and copy section

OS:- Windows, Mac, iOS, Android
Browsers:- Chrome, Firefox, Safari, Edge, UC, Samsung

URL:- https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-sections-leadspace--default-with-no-image

![Spacing issue with headline and copy text in leadspace on mobile.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/151dd4c4-b222-4a13-b11c-7668f39de44d)

**Comment by andysherman2121** [comment]
@chetankan Hey could you guys retest this one too. I think this one was fixed since the issue was opened. Thanks

**Comment by chetankan** [comment]
@andysherman2121  Re-tested in both env staging and react-experimental still issue persist. I have attached screen shot![Leadspace with more than two lines of copy and title .png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/ecf699ed-1ea1-461a-ab67-0962e825b352)![Leadspace with more than two lines of text in copy and title staging.png](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/174aded2-55d8-49b4-a09c-1f1255eac6f9)

**Comment by andysherman2121** [comment]
@chetankan I'm not sure why you guys are seeing this.  I'm not able to replicate the issue. Here's a screenshot of what I'm seeing when trying to replicate 

<img width="548" alt="Screen Shot 2020-03-25 at 1 29 57 PM" src="https://user-images.githubusercontent.com/56688604/77566915-c064b380-6e9c-11ea-843a-3cb96fd403f0.png">

**Comment by chetankan** [comment]
@andysherman2121 :- Spacing issue happens on selecting 'Small' and 'Left' in 'Type' under knobs.With centered there is no spacing issue.

**Comment by andysherman2121** [comment]
@ljcarot @wonilsuhibm @jeffchew Hey guys, I've gone over this issue a few times. Appears to work correctly to me on both staging environment and local (including browserstack testing). If it wasn't working though i'm still not sure if this is even a bug. We don't want our adopters to be adding tons of header text anyways. I've talked with Jeff about closing this and he agreed, but wanted to get your opinions before moving forward.

**Comment by jeffchew** [comment]
> @ljcarot @wonilsuhibm @jeffchew Hey guys, I've gone over this issue a few times. Appears to work correctly to me on both staging environment and local (including browserstack testing). If it wasn't working though i'm still not sure if this is even a bug. We don't want our adopters to be adding tons of header text anyways. I've talked with Jeff about closing this and he agreed, but wanted to get your opinions before moving forward.

I'm ok with closing this if others are.

**Comment by wonilsuhibm** [comment]
I'm seeing this on [this storybook](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/patterns-sections-leadspace--default-with-no-image)

<img width="570" alt="Screen Shot 2020-04-06 at 1 24 49 PM" src="https://user-images.githubusercontent.com/30183447/78586823-09582880-780a-11ea-9dc5-82ebceb7f661.png">

**Comment by andysherman2121** [comment]
@wonilsuhibm What screen size/type are you seeing this on

**Comment by wonilsuhibm** [comment]
It seems that this is happening only under 318px. I think this is a non-issue. @andysherman2121 please ignore.

**Comment by andysherman2121** [comment]
@ljcarot @wonilsuhibm @jeffchew So are we all okay with closing this issue?
